// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * ToolInfo is a serialisable summary of a registered MCP tool, used by the
 * frontend to display the tool catalogue.
 */
export class ToolInfo {
    "name": string;
    "description": string;
    "clearance": string;
    "schema": json$0.RawMessage;

    /** Creates a new ToolInfo instance. */
    constructor($$source: Partial<ToolInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("clearance" in $$source)) {
            this["clearance"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolInfo($$parsedSource as Partial<ToolInfo>);
    }
}
