// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Approval records a Boss decision on a pending request.
 */
export class Approval {
    /**
     * Creates a new Approval instance.
     * @param {Partial<Approval>} [$$source = {}] - The source object to create the Approval.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * hiring, skill_promotion, sudo
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("subject_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject_id"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * pending, approved, rejected
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["decided_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Approval instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Approval}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Approval(/** @type {Partial<Approval>} */($$parsedSource));
    }
}

/**
 * LogTier controls which event stream a log record is sent to.
 * @readonly
 * @enum {string}
 */
export const LogTier = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * TierSummary routes to the Group Chat (Boss-visible).
     */
    TierSummary: "summary",

    /**
     * TierRaw routes to the Engine Room console (Dev Mode only).
     */
    TierRaw: "raw",
};

/**
 * Message is a single entry in the conversation ledger.
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_id"] = "";
        }
        if (!("conversation_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversation_id"] = "";
        }
        if (!("agent_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {MessageKind}
             */
            this["kind"] = MessageKind.$zero;
        }
        if (!("tier" in $$source)) {
            /**
             * @member
             * @type {LogTier}
             */
            this["tier"] = LogTier.$zero;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("metadata" in $$source)) {
            /**
             * JSON blob for tool call details etc.
             * @member
             * @type {string}
             */
            this["metadata"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * MessageKind classifies a message in the conversation stream.
 * @readonly
 * @enum {string}
 */
export const MessageKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    KindBossCommand: "boss_command",
    KindAgentMessage: "agent_message",
    KindToolCall: "tool_call",
    KindToolResult: "tool_result",
    KindMilestone: "milestone",
    KindSystemEvent: "system_event",

    /**
     * Lead-internal, not shown to Boss
     */
    KindDraft: "draft",
};

/**
 * Project represents an isolated workspace.
 */
export class Project {
    /**
     * Creates a new Project instance.
     * @param {Partial<Project>} [$$source = {}] - The source object to create the Project.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("data_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data_path"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Project}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project(/** @type {Partial<Project>} */($$parsedSource));
    }
}
