// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Approval records a Boss decision on a pending request.
 */
export class Approval {
    "id": string;
    "project_id": string;

    /**
     * hiring, skill_promotion, sudo
     */
    "kind": string;
    "subject_id": string;
    "description": string;

    /**
     * pending, approved, rejected
     */
    "status": string;
    "created_at": time$0.Time;
    "decided_at"?: time$0.Time | null;

    /** Creates a new Approval instance. */
    constructor($$source: Partial<Approval> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("subject_id" in $$source)) {
            this["subject_id"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Approval instance from a string or object.
     */
    static createFrom($$source: any = {}): Approval {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Approval($$parsedSource as Partial<Approval>);
    }
}

/**
 * LogTier controls which event stream a log record is sent to.
 */
export enum LogTier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TierSummary routes to the Group Chat (Boss-visible).
     */
    TierSummary = "summary",

    /**
     * TierRaw routes to the Engine Room console (Dev Mode only).
     */
    TierRaw = "raw",
};

/**
 * Message is a single entry in the conversation ledger.
 */
export class Message {
    "id": string;
    "project_id": string;
    "conversation_id": string;
    "agent_id": string;
    "kind": MessageKind;
    "tier": LogTier;
    "content": string;

    /**
     * JSON blob for tool call details etc.
     */
    "metadata": string;
    "created_at": time$0.Time;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("conversation_id" in $$source)) {
            this["conversation_id"] = "";
        }
        if (!("agent_id" in $$source)) {
            this["agent_id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = MessageKind.$zero;
        }
        if (!("tier" in $$source)) {
            this["tier"] = LogTier.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * MessageKind classifies a message in the conversation stream.
 */
export enum MessageKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindBossCommand = "boss_command",
    KindAgentMessage = "agent_message",
    KindToolCall = "tool_call",
    KindToolResult = "tool_result",
    KindMilestone = "milestone",
    KindSystemEvent = "system_event",

    /**
     * Lead-internal, not shown to Boss
     */
    KindDraft = "draft",
};

/**
 * Project represents an isolated workspace.
 */
export class Project {
    "id": string;
    "name": string;
    "description": string;
    "data_path": string;
    "active": boolean;
    "created_at": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("data_path" in $$source)) {
            this["data_path"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}
