// Package memory provides agent memory via vector embeddings stored in SQLite.
// Embeddings are generated by Ollama and stored as JSON arrays of float32.
// Cosine similarity is computed in Go at query time.
package memory

import (
	"context"
	"log/slog"
	"sort"
	"strings"
	"time"

	"github.com/haepapa/kotui/internal/store"
)

const (
	minSimilarity   = float32(0.3)
	feedbackBoost   = float32(1.2)
	indexTimeout    = 30 * time.Second
)

// Embedder generates text embeddings.
type Embedder interface {
	Embed(ctx context.Context, model, text string) ([]float32, error)
}

// Store manages journal embeddings and semantic recall.
type Store struct {
	db       *store.DB
	embedder Embedder
	model    string
	log      *slog.Logger
}

// New creates a memory Store.
func New(db *store.DB, embedder Embedder, model string, log *slog.Logger) *Store {
	if log == nil {
		log = slog.Default()
	}
	return &Store{db: db, embedder: embedder, model: model, log: log}
}

// IndexAsync embeds the text and stores it in the background (non-blocking).
// isFeedback: true for Boss DM feedback (gets ranking boost on recall).
func (s *Store) IndexAsync(ctx context.Context, agentID, projectID, content string, isFeedback bool) {
	go func() {
		embedCtx, cancel := context.WithTimeout(context.Background(), indexTimeout)
		defer cancel()

		vec, err := s.embedder.Embed(embedCtx, s.model, content)
		if err != nil {
			s.log.Warn("memory: index failed (embed)", "agent", agentID, "err", err)
			return
		}

		e := store.JournalEmbedding{
			ID:         store.NewID(),
			AgentID:    agentID,
			ProjectID:  projectID,
			Content:    content,
			Embedding:  vec,
			IsFeedback: isFeedback,
		}
		if err := s.db.SaveJournalEmbedding(embedCtx, e); err != nil {
			s.log.Warn("memory: index failed (save)", "agent", agentID, "err", err)
		}
	}()
}

// Recall returns the top-k most similar entries to the query from the agent's journal.
// Feedback entries get a 1.2× similarity boost.
// Only entries with boosted similarity > 0.3 are returned.
func (s *Store) Recall(ctx context.Context, agentID, projectID, query string, topK int) ([]store.JournalEmbedding, error) {
	queryVec, err := s.embedder.Embed(ctx, s.model, query)
	if err != nil {
		return nil, err
	}

	entries, err := s.db.ListJournalEmbeddings(ctx, agentID, projectID)
	if err != nil {
		return nil, err
	}

	type scored struct {
		entry store.JournalEmbedding
		score float32
	}
	var candidates []scored
	for _, e := range entries {
		if len(e.Embedding) != len(queryVec) {
			continue
		}
		sim := cosine(queryVec, e.Embedding)
		if e.IsFeedback {
			sim *= feedbackBoost
		}
		if sim > minSimilarity {
			candidates = append(candidates, scored{e, sim})
		}
	}

	sort.Slice(candidates, func(i, j int) bool {
		return candidates[i].score > candidates[j].score
	})

	if topK > len(candidates) {
		topK = len(candidates)
	}
	result := make([]store.JournalEmbedding, topK)
	for i := range result {
		result[i] = candidates[i].entry
	}
	return result, nil
}

// FormatRecall formats a list of journal entries as a "Past Experience" markdown
// block suitable for injecting into an agent's context.
// Returns empty string if entries is empty.
func FormatRecall(entries []store.JournalEmbedding) string {
	if len(entries) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("## Past Experience\n\n")
	sb.WriteString("The following relevant journal entries may inform your approach:\n\n")
	for _, e := range entries {
		if e.IsFeedback {
			sb.WriteString("**[BOSS FEEDBACK]** ")
		} else {
			sb.WriteString("**[Journal]** ")
		}
		sb.WriteString(e.Content)
		sb.WriteString("\n\n")
	}
	sb.WriteString("---")
	return sb.String()
}
