// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AgentInfo summarises a known agent's current state for the UI.
 */
export class AgentInfo {
    "id": string;
    "name": string;
    "role": string;

    /**
     * idle | working | parked | offline
     */
    "status": string;
    "model": string;

    /** Creates a new AgentInfo instance. */
    constructor($$source: Partial<AgentInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentInfo($$parsedSource as Partial<AgentInfo>);
    }
}

/**
 * HeartbeatState captures the current system health for the bottom bar.
 */
export class HeartbeatState {
    "is_healthy": boolean;
    "phase": string;
    "breadcrumbs": string[];
    "active_count": number;
    "vram_profile": string;
    "updated_at": time$0.Time;

    /** Creates a new HeartbeatState instance. */
    constructor($$source: Partial<HeartbeatState> = {}) {
        if (!("is_healthy" in $$source)) {
            this["is_healthy"] = false;
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("breadcrumbs" in $$source)) {
            this["breadcrumbs"] = [];
        }
        if (!("active_count" in $$source)) {
            this["active_count"] = 0;
        }
        if (!("vram_profile" in $$source)) {
            this["vram_profile"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeartbeatState instance from a string or object.
     */
    static createFrom($$source: any = {}): HeartbeatState {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("breadcrumbs" in $$parsedSource) {
            $$parsedSource["breadcrumbs"] = $$createField2_0($$parsedSource["breadcrumbs"]);
        }
        return new HeartbeatState($$parsedSource as Partial<HeartbeatState>);
    }
}

/**
 * UIConfig is a flat serialisable struct covering all user-editable settings.
 */
export class UIConfig {
    "ollama_endpoint": string;
    "lead_model": string;
    "worker_model": string;
    "embedder_model": string;
    "senior_model": string;
    "senior_endpoint": string;
    "senior_ssh_host": string;
    "senior_ssh_cmd": string;
    "timezone": string;
    "telegram_bot_token": string;
    "slack_bot_token": string;
    "slack_channel_id": string;
    "webhook_secret": string;

    /** Creates a new UIConfig instance. */
    constructor($$source: Partial<UIConfig> = {}) {
        if (!("ollama_endpoint" in $$source)) {
            this["ollama_endpoint"] = "";
        }
        if (!("lead_model" in $$source)) {
            this["lead_model"] = "";
        }
        if (!("worker_model" in $$source)) {
            this["worker_model"] = "";
        }
        if (!("embedder_model" in $$source)) {
            this["embedder_model"] = "";
        }
        if (!("senior_model" in $$source)) {
            this["senior_model"] = "";
        }
        if (!("senior_endpoint" in $$source)) {
            this["senior_endpoint"] = "";
        }
        if (!("senior_ssh_host" in $$source)) {
            this["senior_ssh_host"] = "";
        }
        if (!("senior_ssh_cmd" in $$source)) {
            this["senior_ssh_cmd"] = "";
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("telegram_bot_token" in $$source)) {
            this["telegram_bot_token"] = "";
        }
        if (!("slack_bot_token" in $$source)) {
            this["slack_bot_token"] = "";
        }
        if (!("slack_channel_id" in $$source)) {
            this["slack_channel_id"] = "";
        }
        if (!("webhook_secret" in $$source)) {
            this["webhook_secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): UIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIConfig($$parsedSource as Partial<UIConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
