// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AgentInfo summarises a known agent's current state for the UI.
 */
export class AgentInfo {
    /**
     * Creates a new AgentInfo instance.
     * @param {Partial<AgentInfo>} [$$source = {}] - The source object to create the AgentInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * idle | working | parked | offline
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentInfo(/** @type {Partial<AgentInfo>} */($$parsedSource));
    }
}

/**
 * HeartbeatState captures the current system health for the bottom bar.
 */
export class HeartbeatState {
    /**
     * Creates a new HeartbeatState instance.
     * @param {Partial<HeartbeatState>} [$$source = {}] - The source object to create the HeartbeatState.
     */
    constructor($$source = {}) {
        if (!("is_healthy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_healthy"] = false;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("breadcrumbs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["breadcrumbs"] = [];
        }
        if (!("active_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active_count"] = 0;
        }
        if (!("vram_profile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vram_profile"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeartbeatState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HeartbeatState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("breadcrumbs" in $$parsedSource) {
            $$parsedSource["breadcrumbs"] = $$createField2_0($$parsedSource["breadcrumbs"]);
        }
        return new HeartbeatState(/** @type {Partial<HeartbeatState>} */($$parsedSource));
    }
}

/**
 * UIConfig is a flat serialisable struct covering all user-editable settings.
 */
export class UIConfig {
    /**
     * Creates a new UIConfig instance.
     * @param {Partial<UIConfig>} [$$source = {}] - The source object to create the UIConfig.
     */
    constructor($$source = {}) {
        if (!("ollama_endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ollama_endpoint"] = "";
        }
        if (!("lead_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lead_model"] = "";
        }
        if (!("worker_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_model"] = "";
        }
        if (!("embedder_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embedder_model"] = "";
        }
        if (!("senior_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["senior_model"] = "";
        }
        if (!("senior_endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["senior_endpoint"] = "";
        }
        if (!("senior_ssh_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["senior_ssh_host"] = "";
        }
        if (!("senior_ssh_cmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["senior_ssh_cmd"] = "";
        }
        if (!("timezone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timezone"] = "";
        }
        if (!("telegram_bot_token" in $$source)) {
            /**
             * Telegram
             * @member
             * @type {string}
             */
            this["telegram_bot_token"] = "";
        }
        if (!("telegram_chat_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["telegram_chat_id"] = "";
        }
        if (!("slack_bot_token" in $$source)) {
            /**
             * Slack
             * @member
             * @type {string}
             */
            this["slack_bot_token"] = "";
        }
        if (!("slack_channel_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slack_channel_id"] = "";
        }
        if (!("slack_signing_secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slack_signing_secret"] = "";
        }
        if (!("whatsapp_token" in $$source)) {
            /**
             * WhatsApp
             * @member
             * @type {string}
             */
            this["whatsapp_token"] = "";
        }
        if (!("whatsapp_phone_number_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["whatsapp_phone_number_id"] = "";
        }
        if (!("whatsapp_verify_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["whatsapp_verify_token"] = "";
        }
        if (!("webhook_secret" in $$source)) {
            /**
             * Shared
             * @member
             * @type {string}
             */
            this["webhook_secret"] = "";
        }
        if (!("webhook_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["webhook_port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UIConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIConfig(/** @type {Partial<UIConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
