// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AgentInfo summarises a known agent's current state for the UI.
 */
export class AgentInfo {
    "id": string;
    "name": string;
    "role": string;

    /**
     * idle | working | parked | offline
     */
    "status": string;
    "model": string;

    /** Creates a new AgentInfo instance. */
    constructor($$source: Partial<AgentInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentInfo($$parsedSource as Partial<AgentInfo>);
    }
}

/**
 * HeartbeatState captures the current system health for the bottom bar.
 */
export class HeartbeatState {
    "is_healthy": boolean;
    "phase": string;
    "breadcrumbs": string[];
    "active_count": number;
    "vram_profile": string;
    "updated_at": time$0.Time;

    /** Creates a new HeartbeatState instance. */
    constructor($$source: Partial<HeartbeatState> = {}) {
        if (!("is_healthy" in $$source)) {
            this["is_healthy"] = false;
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("breadcrumbs" in $$source)) {
            this["breadcrumbs"] = [];
        }
        if (!("active_count" in $$source)) {
            this["active_count"] = 0;
        }
        if (!("vram_profile" in $$source)) {
            this["vram_profile"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeartbeatState instance from a string or object.
     */
    static createFrom($$source: any = {}): HeartbeatState {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("breadcrumbs" in $$parsedSource) {
            $$parsedSource["breadcrumbs"] = $$createField2_0($$parsedSource["breadcrumbs"]);
        }
        return new HeartbeatState($$parsedSource as Partial<HeartbeatState>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
