// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WarRoomService is the Wails-registered service binding.
 * All exported methods become callable from TypeScript via Call.ByName.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../pkg/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArchiveProject hides a project from the sidebar. If the project is active,
 * the next project becomes active; if none remain, the UI shows an empty state.
 */
export function ArchiveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(3600507192, id);
}

/**
 * CreateProject creates a new project, marks it active, and switches to it.
 */
export function CreateProject(name: string, description: string): $CancellablePromise<models$0.Project | null> {
    return $Call.ByID(3685735424, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DecideApproval approves or rejects a pending approval.
 * decision must be "approved" or "rejected".
 */
export function DecideApproval(id: string, decision: string): $CancellablePromise<void> {
    return $Call.ByID(3594396176, id, decision);
}

/**
 * DeleteOllamaModel deletes a locally-stored model by name.
 * Pass an empty endpoint to use the configured local endpoint.
 */
export function DeleteOllamaModel(endpoint: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2592936139, endpoint, name);
}

/**
 * DeleteSandboxFile removes a file (or empty directory) from the agent workspace.
 */
export function DeleteSandboxFile(relPath: string): $CancellablePromise<void> {
    return $Call.ByID(1612808497, relPath);
}

/**
 * EmitBrainUpdate records a system_event in the agent's DM conversation and
 * fires a kotui:brain_update event so the frontend can update the unread badge.
 * Called both from SaveAgentBrainFile (user-initiated) and from the update_self
 * MCP tool callback (agent-initiated).
 */
export function EmitBrainUpdate(agentID: string, file: string, summary: string): $CancellablePromise<void> {
    return $Call.ByID(2104978325, agentID, file, summary);
}

/**
 * EmitPendingApprovals loads and broadcasts all pending approvals for a project.
 * Called by the orchestrator's LeadOptimizer when a new handbook proposal is created.
 */
export function EmitPendingApprovals(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(882949697, projectID);
}

/**
 * EmitQueueState fires a kotui:queue_state event so the frontend can display
 * the current cognition queue depth and activity. Called from the orchestrator's
 * OnQueueState callback on every enqueue/dequeue/execution state change.
 * This method must be non-blocking — it is called from the queue dispatcher goroutine.
 */
export function EmitQueueState(p0: number, p1: number, p2: number, p3: number, active: boolean, throttled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2488856920, p0, p1, p2, p3, active, throttled);
}

/**
 * GetActiveConversation returns the conversation ID for the active project.
 */
export function GetActiveConversation(): $CancellablePromise<string> {
    return $Call.ByID(1586175064);
}

/**
 * GetAgentBrainFiles returns the three editable brain files for the given agent.
 * Results are served from the in-memory IdentityRegistry (cache-warm: no disk
 * I/O). The cache is invalidated whenever a file is saved or the agent updates
 * its own brain via the update_self tool, so callers always see current content.
 * If the brain files don't exist yet (e.g. first run before first chat), they
 * are initialised with defaults so the panel always has content to show.
 */
export function GetAgentBrainFiles(agentID: string): $CancellablePromise<$models.BrainFiles> {
    return $Call.ByID(3948791757, agentID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAgentJournalFile returns the content of a single journal file.
 * filename must be a plain filename (no path separators) to prevent path traversal.
 */
export function GetAgentJournalFile(agentID: string, filename: string): $CancellablePromise<string> {
    return $Call.ByID(1484584703, agentID, filename);
}

/**
 * GetAgentJournalFiles returns a sorted list of journal filenames for the given agent.
 * Journal files live in {dataDir}/agents/{agentID}/journal/. Returns an empty slice
 * (not an error) when no journal entries exist yet.
 */
export function GetAgentJournalFiles(agentID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3635945060, agentID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetAgents returns the current agent roster for the active project.
 */
export function GetAgents(): $CancellablePromise<$models.AgentInfo[]> {
    return $Call.ByID(1767502295).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetCompanyIdentity returns the content of COMPANY_IDENTITY.md.
 * When the file does not exist or is empty, a starter template is returned.
 */
export function GetCompanyIdentity(): $CancellablePromise<string> {
    return $Call.ByID(1837997534);
}

export function GetConfig(): $CancellablePromise<$models.UIConfig> {
    return $Call.ByID(3551944047).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetHandbook returns the content of handbook.md.
 * When no user-edited copy exists on disk, the embedded handbook is returned.
 */
export function GetHandbook(): $CancellablePromise<string> {
    return $Call.ByID(1655511949);
}

/**
 * GetHeartbeat returns the current heartbeat state snapshot.
 */
export function GetHeartbeat(): $CancellablePromise<$models.HeartbeatState> {
    return $Call.ByID(3900598671).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetMessages returns messages for a conversation, newest last.
 * Pass limit ≤ 0 to return all.
 */
export function GetMessages(conversationID: string, limit: number): $CancellablePromise<models$0.Message[]> {
    return $Call.ByID(2715906237, conversationID, limit).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetOrCreateDirectConversation returns or creates a DM conversation for the given agent.
 * DM conversations are agent-global — the same conversation is reused regardless of
 * which project is currently active. The first time a DM is opened for an agent the
 * conversation is created inside the active project (for FK integrity), but on every
 * subsequent call the existing conversation is returned irrespective of active project.
 */
export function GetOrCreateDirectConversation(agentID: string): $CancellablePromise<string> {
    return $Call.ByID(2646181570, agentID);
}

/**
 * GetPendingApprovals returns all pending approvals for the active project.
 */
export function GetPendingApprovals(): $CancellablePromise<models$0.Approval[]> {
    return $Call.ByID(2250532500).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetProjects returns all projects ordered by creation date (newest first).
 */
export function GetProjects(): $CancellablePromise<models$0.Project[]> {
    return $Call.ByID(634004591).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * InitFirstRun checks whether the app has been used before.
 * On a fresh install (no projects exist) it creates a default "General" project,
 * opens a Lead DM conversation, and saves a welcome greeting so the user has an
 * immediate call to action in the sidebar. Subsequent calls are no-ops.
 */
export function InitFirstRun(): $CancellablePromise<$models.FirstRunResult> {
    return $Call.ByID(787017174).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ListOllamaModels returns all model names available on the given Ollama endpoint.
 * Pass an empty endpoint to use the configured local endpoint.
 * Returns an error with the prefix "no endpoint" if endpoint is the sentinel value "none".
 */
export function ListOllamaModels(endpoint: string): $CancellablePromise<string[]> {
    return $Call.ByID(637971051, endpoint).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListSandboxFiles returns the files and directories in the agent workspace.
 * The list is sorted: directories first (alphabetically), then files.
 * Returns an empty slice (not an error) when the sandbox does not exist yet.
 */
export function ListSandboxFiles(): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(1919929905).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * PullOllamaModel pulls a model by name from the Ollama registry.
 * Pass an empty endpoint to use the configured local endpoint.
 * Pull can take several minutes.
 */
export function PullOllamaModel(endpoint: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2538362535, endpoint, name);
}

/**
 * ReadSandboxFile returns the text content of a file in the agent workspace.
 * Returns an error if the resolved path escapes the sandbox or the file exceeds 512 KB.
 */
export function ReadSandboxFile(relPath: string): $CancellablePromise<string> {
    return $Call.ByID(3782088252, relPath);
}

/**
 * RenameProject updates the name and description of an existing project.
 */
export function RenameProject(id: string, name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(1347916226, id, name, description);
}

/**
 * RenameSandboxFile renames a file or directory within the sandbox.
 * newName must be a plain file/directory name (no path separators).
 */
export function RenameSandboxFile(relPath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(589647294, relPath, newName);
}

/**
 * ResetAppData wipes all user data and resets the configuration to defaults.
 * This deletes all chat history, projects, agents, agent identity files, and
 * resets config.toml. The caller must restart (or reload) the app afterwards.
 */
export function ResetAppData(): $CancellablePromise<void> {
    return $Call.ByID(4104306593);
}

/**
 * RevealSandboxFile opens the OS file explorer and selects/highlights the file.
 * On macOS this opens Finder; on Linux it opens the parent directory in the
 * default file manager; on Windows it opens Explorer with the file selected.
 */
export function RevealSandboxFile(relPath: string): $CancellablePromise<void> {
    return $Call.ByID(820944791, relPath);
}

/**
 * SaveAgentBrainFile writes one brain file (soul, persona, or skills) for the
 * given agent, then recomposes instruction.md and invalidates the DM agent
 * cache so the next message picks up the updated prompt.
 * summary is a short human-readable description of the change shown in the DM.
 */
export function SaveAgentBrainFile(agentID: string, fileKey: string, content: string, summary: string): $CancellablePromise<void> {
    return $Call.ByID(2159223175, agentID, fileKey, content, summary);
}

/**
 * SaveCompanyIdentity writes COMPANY_IDENTITY.md and triggers CultureBroadcast.
 */
export function SaveCompanyIdentity(content: string): $CancellablePromise<void> {
    return $Call.ByID(3651828523, content);
}

/**
 * SaveConfig writes updated settings to disk.
 * Changes take effect on the next app start.
 */
export function SaveConfig(uiCfg: $models.UIConfig): $CancellablePromise<void> {
    return $Call.ByID(2733362488, uiCfg);
}

/**
 * SaveHandbook writes handbook.md and triggers HandbookBroadcast.
 */
export function SaveHandbook(content: string): $CancellablePromise<void> {
    return $Call.ByID(2139692174, content);
}

/**
 * SendBossCommand enqueues a Boss instruction to the Orchestrator.
 * Returns immediately; responses arrive via kotui:message events.
 * Token chunks are streamed to the frontend via kotui:channel_stream so the
 * channel chat has the same live typing effect as DM conversations.
 * 
 * Like SendDirectMessage, commands sent while a response is in-flight are
 * batched and delivered as a single combined request.
 */
export function SendBossCommand(command: string): $CancellablePromise<void> {
    return $Call.ByID(3294220229, command);
}

/**
 * SendDirectMessage sends a message directly to a specific agent and routes the
 * response back to the DM conversation window — bypassing the Lead/Worker pipeline.
 * 
 * If a response is already in-flight for this agent, the new message is batched
 * with any other pending messages and delivered as a single combined request when
 * the current inference completes. This reduces LLM round-trips and gives the
 * model the full conversation context.
 */
export function SendDirectMessage(agentID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3506599419, agentID, message);
}

/**
 * SetSudoDecideHook registers a callback that is called when the Boss approves
 * or rejects a sudo command approval (kind="sudo"). gui.go wires this to
 * SudoGate.Resolve after both the gate and service are created.
 */
export function SetSudoDecideHook(fn: any): $CancellablePromise<void> {
    return $Call.ByID(1352021911, fn);
}

/**
 * Shutdown stops the event bridge and health monitor. Called on app teardown.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(998849289);
}

/**
 * SwitchProject marks a project as active and resets the Orchestrator context.
 */
export function SwitchProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(4089460832, id);
}

// Private type creation functions
const $$createType0 = models$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BrainFiles.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.AgentInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.UIConfig.createFrom;
const $$createType7 = $models.HeartbeatState.createFrom;
const $$createType8 = models$0.Message.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.Approval.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = $models.FirstRunResult.createFrom;
const $$createType14 = $models.FileEntry.createFrom;
const $$createType15 = $Create.Array($$createType14);
