// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WarRoomService is the Wails-registered service binding.
 * All exported methods become callable from TypeScript via Call.ByName.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../pkg/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArchiveProject hides a project from the sidebar. If the project is active,
 * the next project becomes active; if none remain, the UI shows an empty state.
 */
export function ArchiveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(3600507192, id);
}

/**
 * CreateProject creates a new project, marks it active, and switches to it.
 */
export function CreateProject(name: string, description: string): $CancellablePromise<models$0.Project | null> {
    return $Call.ByID(3685735424, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DecideApproval approves or rejects a pending approval.
 * decision must be "approved" or "rejected".
 */
export function DecideApproval(id: string, decision: string): $CancellablePromise<void> {
    return $Call.ByID(3594396176, id, decision);
}

/**
 * DeleteOllamaModel deletes a locally-stored model by name.
 * Pass an empty endpoint to use the configured local endpoint.
 */
export function DeleteOllamaModel(endpoint: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2592936139, endpoint, name);
}

/**
 * GetActiveConversation returns the conversation ID for the active project.
 */
export function GetActiveConversation(): $CancellablePromise<string> {
    return $Call.ByID(1586175064);
}

/**
 * GetAgents returns the current agent roster for the active project.
 */
export function GetAgents(): $CancellablePromise<$models.AgentInfo[]> {
    return $Call.ByID(1767502295).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetCompanyIdentity returns the content of COMPANY_IDENTITY.md.
 * When the file does not exist or is empty, a starter template is returned.
 */
export function GetCompanyIdentity(): $CancellablePromise<string> {
    return $Call.ByID(1837997534);
}

/**
 * GetConfig returns the current configuration as a flat UIConfig.
 */
export function GetConfig(): $CancellablePromise<$models.UIConfig> {
    return $Call.ByID(3551944047).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetHeartbeat returns the current heartbeat state snapshot.
 */
export function GetHeartbeat(): $CancellablePromise<$models.HeartbeatState> {
    return $Call.ByID(3900598671).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetMessages returns messages for a conversation, newest last.
 * Pass limit ≤ 0 to return all.
 */
export function GetMessages(conversationID: string, limit: number): $CancellablePromise<models$0.Message[]> {
    return $Call.ByID(2715906237, conversationID, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetOrCreateDirectConversation returns or creates a DM conversation for the given agent.
 * DM conversations are agent-global — the same conversation is reused regardless of
 * which project is currently active. The first time a DM is opened for an agent the
 * conversation is created inside the active project (for FK integrity), but on every
 * subsequent call the existing conversation is returned irrespective of active project.
 */
export function GetOrCreateDirectConversation(agentID: string): $CancellablePromise<string> {
    return $Call.ByID(2646181570, agentID);
}

/**
 * GetPendingApprovals returns all pending approvals for the active project.
 */
export function GetPendingApprovals(): $CancellablePromise<models$0.Approval[]> {
    return $Call.ByID(2250532500).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetProjects returns all projects ordered by creation date (newest first).
 */
export function GetProjects(): $CancellablePromise<models$0.Project[]> {
    return $Call.ByID(634004591).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListOllamaModels returns all model names available on the given Ollama endpoint.
 * Pass an empty endpoint to use the configured local endpoint.
 * Returns an error with the prefix "no endpoint" if endpoint is the sentinel value "none".
 */
export function ListOllamaModels(endpoint: string): $CancellablePromise<string[]> {
    return $Call.ByID(637971051, endpoint).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * PullOllamaModel pulls a model by name from the Ollama registry.
 * Pass an empty endpoint to use the configured local endpoint.
 * Pull can take several minutes.
 */
export function PullOllamaModel(endpoint: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2538362535, endpoint, name);
}

/**
 * RenameProject updates the name and description of an existing project.
 */
export function RenameProject(id: string, name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(1347916226, id, name, description);
}

/**
 * SaveCompanyIdentity writes COMPANY_IDENTITY.md and triggers CultureBroadcast.
 */
export function SaveCompanyIdentity(content: string): $CancellablePromise<void> {
    return $Call.ByID(3651828523, content);
}

/**
 * SaveConfig writes updated settings to disk.
 * Changes take effect on the next app start.
 */
export function SaveConfig(uiCfg: $models.UIConfig): $CancellablePromise<void> {
    return $Call.ByID(2733362488, uiCfg);
}

/**
 * SendBossCommand enqueues a Boss instruction to the Orchestrator.
 * Returns immediately; responses arrive via kotui:message events.
 */
export function SendBossCommand(command: string): $CancellablePromise<void> {
    return $Call.ByID(3294220229, command);
}

/**
 * SendDirectMessage sends a message directly to a specific agent and routes the
 * response back to the DM conversation window — bypassing the Lead/Worker pipeline.
 */
export function SendDirectMessage(agentID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3506599419, agentID, message);
}

/**
 * Shutdown stops the event bridge and health monitor. Called on app teardown.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(998849289);
}

/**
 * SwitchProject marks a project as active and resets the Orchestrator context.
 */
export function SwitchProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(4089460832, id);
}

// Private type creation functions
const $$createType0 = models$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AgentInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.UIConfig.createFrom;
const $$createType5 = $models.HeartbeatState.createFrom;
const $$createType6 = models$0.Message.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.Approval.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType0);
const $$createType11 = $Create.Array($Create.Any);
