// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WarRoomService is the Wails-registered service binding.
 * All exported methods become callable from TypeScript via Call.ByName.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../pkg/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateProject creates a new project, marks it active, and switches to it.
 */
export function CreateProject(name: string, description: string): $CancellablePromise<models$0.Project | null> {
    return $Call.ByID(3685735424, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetActiveConversation returns the conversation ID for the active project.
 */
export function GetActiveConversation(): $CancellablePromise<string> {
    return $Call.ByID(1586175064);
}

/**
 * GetAgents returns the current agent roster for the active project.
 */
export function GetAgents(): $CancellablePromise<$models.AgentInfo[]> {
    return $Call.ByID(1767502295).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetHeartbeat returns the current heartbeat state snapshot.
 */
export function GetHeartbeat(): $CancellablePromise<$models.HeartbeatState> {
    return $Call.ByID(3900598671).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetMessages returns messages for a conversation, newest last.
 * Pass limit ≤ 0 to return all.
 */
export function GetMessages(conversationID: string, limit: number): $CancellablePromise<models$0.Message[]> {
    return $Call.ByID(2715906237, conversationID, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetProjects returns all projects ordered by creation date (newest first).
 */
export function GetProjects(): $CancellablePromise<models$0.Project[]> {
    return $Call.ByID(634004591).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SendBossCommand enqueues a Boss instruction to the Orchestrator.
 * Returns immediately; responses arrive via kotui:message events.
 */
export function SendBossCommand(command: string): $CancellablePromise<void> {
    return $Call.ByID(3294220229, command);
}

/**
 * Shutdown stops the event bridge. Called on app teardown.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(998849289);
}

/**
 * SwitchProject marks a project as active and resets the Orchestrator context.
 */
export function SwitchProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(4089460832, id);
}

// Private type creation functions
const $$createType0 = models$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AgentInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.HeartbeatState.createFrom;
const $$createType5 = models$0.Message.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType0);
