// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WarRoomService is the Wails-registered service binding.
 * All exported methods become callable from TypeScript via Call.ByName.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../pkg/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArchiveProject hides a project from the sidebar. If the project is active,
 * the next project becomes active; if none remain, the UI shows an empty state.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveProject(id) {
    return $Call.ByID(3600507192, id);
}

/**
 * CreateProject creates a new project, marks it active, and switches to it.
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<models$0.Project | null>}
 */
export function CreateProject(name, description) {
    return $Call.ByID(3685735424, name, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DecideApproval approves or rejects a pending approval.
 * decision must be "approved" or "rejected".
 * @param {string} id
 * @param {string} decision
 * @returns {$CancellablePromise<void>}
 */
export function DecideApproval(id, decision) {
    return $Call.ByID(3594396176, id, decision);
}

/**
 * DeleteOllamaModel deletes a locally-stored model by name.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteOllamaModel(name) {
    return $Call.ByID(2592936139, name);
}

/**
 * GetActiveConversation returns the conversation ID for the active project.
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveConversation() {
    return $Call.ByID(1586175064);
}

/**
 * GetAgents returns the current agent roster for the active project.
 * @returns {$CancellablePromise<$models.AgentInfo[]>}
 */
export function GetAgents() {
    return $Call.ByID(1767502295).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCompanyIdentity returns the content of COMPANY_IDENTITY.md.
 * @returns {$CancellablePromise<string>}
 */
export function GetCompanyIdentity() {
    return $Call.ByID(1837997534);
}

/**
 * GetConfig returns the current configuration as a flat UIConfig.
 * @returns {$CancellablePromise<$models.UIConfig>}
 */
export function GetConfig() {
    return $Call.ByID(3551944047).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetHeartbeat returns the current heartbeat state snapshot.
 * @returns {$CancellablePromise<$models.HeartbeatState>}
 */
export function GetHeartbeat() {
    return $Call.ByID(3900598671).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetMessages returns messages for a conversation, newest last.
 * Pass limit ≤ 0 to return all.
 * @param {string} conversationID
 * @param {number} limit
 * @returns {$CancellablePromise<models$0.Message[]>}
 */
export function GetMessages(conversationID, limit) {
    return $Call.ByID(2715906237, conversationID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetOrCreateDirectConversation returns or creates a DM conversation for the given agent.
 * @param {string} agentID
 * @returns {$CancellablePromise<string>}
 */
export function GetOrCreateDirectConversation(agentID) {
    return $Call.ByID(2646181570, agentID);
}

/**
 * GetPendingApprovals returns all pending approvals for the active project.
 * @returns {$CancellablePromise<models$0.Approval[]>}
 */
export function GetPendingApprovals() {
    return $Call.ByID(2250532500).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetProjects returns all projects ordered by creation date (newest first).
 * @returns {$CancellablePromise<models$0.Project[]>}
 */
export function GetProjects() {
    return $Call.ByID(634004591).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListOllamaModels returns all model names available on the given Ollama endpoint.
 * Pass an empty endpoint to use the configured local endpoint.
 * @param {string} endpoint
 * @returns {$CancellablePromise<string[]>}
 */
export function ListOllamaModels(endpoint) {
    return $Call.ByID(637971051, endpoint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * PullOllamaModel pulls a model by name from the Ollama registry.
 * Uses the configured local endpoint. Pull can take several minutes.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function PullOllamaModel(name) {
    return $Call.ByID(2538362535, name);
}

/**
 * RenameProject updates the name and description of an existing project.
 * @param {string} id
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<void>}
 */
export function RenameProject(id, name, description) {
    return $Call.ByID(1347916226, id, name, description);
}

/**
 * SaveCompanyIdentity writes COMPANY_IDENTITY.md and triggers CultureBroadcast.
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveCompanyIdentity(content) {
    return $Call.ByID(3651828523, content);
}

/**
 * SaveConfig writes updated settings to disk.
 * Changes take effect on the next app start.
 * @param {$models.UIConfig} uiCfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(uiCfg) {
    return $Call.ByID(2733362488, uiCfg);
}

/**
 * SendBossCommand enqueues a Boss instruction to the Orchestrator.
 * Returns immediately; responses arrive via kotui:message events.
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function SendBossCommand(command) {
    return $Call.ByID(3294220229, command);
}

/**
 * SendDirectMessage sends a direct feedback message to a specific agent.
 * @param {string} agentID
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendDirectMessage(agentID, message) {
    return $Call.ByID(3506599419, agentID, message);
}

/**
 * Shutdown stops the event bridge. Called on app teardown.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(998849289);
}

/**
 * SwitchProject marks a project as active and resets the Orchestrator context.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SwitchProject(id) {
    return $Call.ByID(4089460832, id);
}

// Private type creation functions
const $$createType0 = models$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AgentInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.UIConfig.createFrom;
const $$createType5 = $models.HeartbeatState.createFrom;
const $$createType6 = models$0.Message.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.Approval.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType0);
const $$createType11 = $Create.Array($Create.Any);
