// @ts-check
// This file is automatically generated by wails3 generate bindings.
// DO NOT EDIT — regenerate by running: wails3 generate bindings -f .

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

function configure() {
    // No custom events registered yet. Events will be added in Phase 7+.
    Object.freeze(Object.assign($Create.Events, {}));
}

configure();
