// @ts-check
// This file is automatically generated by wails3 generate bindings.
// DO NOT EDIT — regenerate by running: wails3 generate bindings -f .
// NOTE: wails3 generate bindings is broken on Go 1.25; custom events are
// maintained manually below.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        // kotui custom events
        "kotui:message":   "kotui:message",
        "kotui:heartbeat": "kotui:heartbeat",
        "kotui:error":     "kotui:error",
        "kotui:agents":    "kotui:agents",
    }));
}

configure();
